import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { DataCenterPage } from "./data-center-page";

const api=vi.hoisted(()=>({listMetrics:vi.fn(),statistics:vi.fn(),accountOptions:vi.fn(),createMetric:vi.fn(),updateMetric:vi.fn(),deleteMetric:vi.fn(),exportMetrics:vi.fn()}));
vi.mock("./api",()=>api);
vi.spyOn(HTMLAnchorElement.prototype,"click").mockImplementation(()=>{});
const account={id:"a0000000-0000-4000-8000-000000000001",organization_id:"o",platform:"小红书",account_name:"数据账号",account_url:null,account_avatar:null,account_type:"品牌账号",positioning:null,target_user:null,operator:null,status:"启用",description:null,created_by:null,updated_by:null,created_at:"2026-08-14T00:00:00Z",updated_at:"2026-08-14T00:00:00Z"};
const metric={id:"m0000000-0000-4000-8000-000000000001",organization_id:"o",account_id:account.id,account_name:"数据账号",platform:"小红书",metric_date:"2026-08-14",content_title:"升学内容",content_url:null,content_type:"图文",publish_time:null,exposure:100,views:80,likes:10,comments:2,favorites:3,shares:1,private_messages:1,new_leads:5,valid_leads:4,high_intent_leads:2,trial_bookings:1,deals:1,revenue:"1999.90",notes:null,created_by:null,updated_by:null,created_at:"2026-08-14T00:00:00Z",updated_at:"2026-08-14T00:00:00Z"};
describe("DataCenterPage",()=>{beforeEach(()=>{vi.clearAllMocks();api.listMetrics.mockResolvedValue({items:[metric],total:1,page:1,page_size:20,total_pages:1});api.statistics.mockResolvedValue({exposure:100,views:80,interactions:16,new_leads:5,valid_leads:4,high_intent_leads:2,trial_bookings:1,deals:1,revenue:"1999.90",interaction_rate:"20.00",valid_lead_rate:"80.00",trial_conversion_rate:"25.00",deal_rate:"25.00"});api.accountOptions.mockResolvedValue({items:[account]});api.createMetric.mockResolvedValue(metric);api.updateMetric.mockResolvedValue(metric);api.deleteMetric.mockResolvedValue(undefined);api.exportMetrics.mockResolvedValue(new Blob(["csv"]));});
it("loads real statistics, filters and table",async()=>{render(<DataCenterPage/>);expect(await screen.findByRole("button",{name:"升学内容"})).toBeInTheDocument();expect(screen.getAllByText("¥1,999.90")).toHaveLength(2);fireEvent.change(screen.getByLabelText("平台筛选"),{target:{value:"小红书"}});await waitFor(()=>expect(api.listMetrics).toHaveBeenLastCalledWith(expect.objectContaining({platform:"小红书"})));});
it("creates and edits data with account selection",async()=>{render(<DataCenterPage/>);await screen.findByRole("button",{name:"升学内容"});fireEvent.click(screen.getByRole("button",{name:"新增数据"}));fireEvent.change(screen.getByLabelText(/账号\*/),{target:{value:account.id}});fireEvent.change(screen.getByLabelText(/内容标题/),{target:{value:"新内容"}});fireEvent.click(screen.getByRole("button",{name:"保存"}));await waitFor(()=>expect(api.createMetric).toHaveBeenCalledWith(expect.objectContaining({account_id:account.id,content_title:"新内容"})));fireEvent.click(screen.getByRole("button",{name:"编辑"}));fireEvent.change(screen.getByLabelText(/内容标题/),{target:{value:"已更新"}});fireEvent.click(screen.getByRole("button",{name:"保存"}));await waitFor(()=>expect(api.updateMetric).toHaveBeenCalledWith(metric.id,expect.objectContaining({content_title:"已更新"})));});
it("deletes after confirmation",async()=>{vi.spyOn(window,"confirm").mockReturnValue(true);render(<DataCenterPage/>);await screen.findByRole("button",{name:"升学内容"});fireEvent.click(screen.getByRole("button",{name:"删除"}));await waitFor(()=>expect(api.deleteMetric).toHaveBeenCalledWith(metric.id));});
it("opens import and exports current filters",async()=>{Object.defineProperty(URL,"createObjectURL",{value:vi.fn(()=>"blob:test"),configurable:true});Object.defineProperty(URL,"revokeObjectURL",{value:vi.fn(),configurable:true});render(<DataCenterPage/>);await screen.findByRole("button",{name:"升学内容"});fireEvent.click(screen.getByRole("button",{name:"导入"}));expect(screen.getByRole("dialog",{name:"导入运营数据"})).toBeInTheDocument();fireEvent.click(screen.getAllByRole("button",{name:"关闭"})[0]);fireEvent.click(screen.getByRole("button",{name:"导出 CSV"}));await waitFor(()=>expect(api.exportMetrics).toHaveBeenCalled());});});
