"use client";
import { useCallback, useEffect, useState } from "react";
import type { Account } from "@/features/accounts/types";
import { ErrorState } from "@/components/ui/error-state";
import { LoadingState } from "@/components/ui/loading-state";
import { PageHeader } from "@/components/ui/page-header";
import { TableContainer } from "@/components/ui/table-container";
import { accountOptions, createMetric, deleteMetric, exportMetrics, listMetrics, statistics, updateMetric } from "./api";
import { ImportDialog } from "./import-dialog";
import { MetricDetailDialog } from "./metric-detail-dialog";
import { MetricFormDialog } from "./metric-form-dialog";
import { emptyMetric, type Metric, type MetricFilters, type MetricList, type MetricWrite, type Statistics } from "./types";

const initial:MetricFilters={page:1,pageSize:20,dateFrom:"",dateTo:"",platform:"",accountId:"",contentType:"",search:""};
const number=(v:number)=>new Intl.NumberFormat("zh-CN").format(v);
const money=(v:string)=>new Intl.NumberFormat("zh-CN",{style:"currency",currency:"CNY"}).format(Number(v));
export function DataCenterPage(){
 const[filters,setFilters]=useState(initial),[search,setSearch]=useState(""),[data,setData]=useState<MetricList|null>(null),[stats,setStats]=useState<Statistics|null>(null),[accounts,setAccounts]=useState<Account[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[form,setForm]=useState<Metric|"create"|null>(null),[detail,setDetail]=useState<Metric|null>(null),[importOpen,setImportOpen]=useState(false),[saving,setSaving]=useState(false),[formError,setFormError]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const[list,summary,accountList]=await Promise.all([listMetrics(filters),statistics(filters),accountOptions()]);setData(list);setStats(summary);setAccounts(accountList.items)}catch(e){setError(e instanceof Error?e.message:"数据加载失败")}finally{setLoading(false)}},[filters]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
 async function save(value:MetricWrite){setSaving(true);setFormError(null);try{if(form==="create")await createMetric(value);else if(form)await updateMetric(form.id,value);setForm(null);await load()}catch(e){setFormError(e instanceof Error?e.message:"保存失败")}finally{setSaving(false)}}
 async function remove(metric:Metric){if(!window.confirm(`确认删除“${metric.content_title}”的数据吗？`))return;try{await deleteMetric(metric.id);await load()}catch(e){setError(e instanceof Error?e.message:"删除失败")}}
 async function download(){try{const blob=await exportMetrics(filters),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download="运营数据.csv";link.click();URL.revokeObjectURL(url)}catch(e){setError(e instanceof Error?e.message:"导出失败")}}
 const cards:[string,keyof Statistics,string?][]=[["总曝光","exposure"],["总播放","views"],["总互动","interactions"],["有效线索","valid_leads"],["试听","trial_bookings"],["成交","deals"],["成交金额","revenue","money"]];
 return <><PageHeader title="数据中心" description="统一管理各平台运营数据。" actions={<><button className="button secondary" onClick={()=>setImportOpen(true)}>导入</button><button className="button secondary" onClick={()=>void download()}>导出 CSV</button><button className="button primary" onClick={()=>setForm("create")}>新增数据</button></>}/><div className="metric-grid data-metrics">{cards.map(([label,key,format])=><div className="metric-card" key={key}><span>{label}</span><strong>{stats?(format?money(String(stats[key])):number(Number(stats[key]))):"—"}</strong></div>)}</div><section className="account-list-card"><Filters filters={filters} search={search} accounts={accounts} setSearch={setSearch} setFilters={setFilters}/>{loading?<LoadingState label="正在加载运营数据…"/>:error?<ErrorState message={error}/>:data?.items.length?<MetricTable data={data} page={filters.page} setPage={page=>setFilters({...filters,page})} onDetail={setDetail} onEdit={setForm} onDelete={remove}/>:<div className="account-empty"><strong>暂无运营数据</strong><p>可以手动新增，或使用标准 CSV/XLSX 模板导入。</p></div>}</section>{form?<MetricFormDialog key={form==="create"?"create":form.id} initial={form==="create"?emptyMetric:form} accounts={accounts} busy={saving} error={formError} onClose={()=>setForm(null)} onSubmit={save}/>:null}{detail?<MetricDetailDialog metric={detail} onClose={()=>setDetail(null)}/>:null}{importOpen?<ImportDialog onClose={()=>setImportOpen(false)} onDone={load}/>:null}</>;
}
function Filters({filters,search,accounts,setSearch,setFilters}:{filters:MetricFilters;search:string;accounts:Account[];setSearch:(v:string)=>void;setFilters:(v:MetricFilters)=>void}){return <div className="filter-bar data-filters"><form onSubmit={e=>{e.preventDefault();setFilters({...filters,page:1,search:search.trim()})}}><input aria-label="搜索运营数据" placeholder="搜索内容标题或备注" value={search} onChange={e=>setSearch(e.target.value)}/><button className="button secondary">搜索</button></form><input aria-label="开始日期" type="date" value={filters.dateFrom} onChange={e=>setFilters({...filters,page:1,dateFrom:e.target.value})}/><input aria-label="结束日期" type="date" value={filters.dateTo} onChange={e=>setFilters({...filters,page:1,dateTo:e.target.value})}/><select aria-label="平台筛选" value={filters.platform} onChange={e=>setFilters({...filters,page:1,platform:e.target.value})}><option value="">全部平台</option>{["小红书","抖音","视频号","公众号","其他"].map(v=><option key={v}>{v}</option>)}</select><select aria-label="账号筛选" value={filters.accountId} onChange={e=>setFilters({...filters,page:1,accountId:e.target.value})}><option value="">全部账号</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.account_name}</option>)}</select><select aria-label="内容类型筛选" value={filters.contentType} onChange={e=>setFilters({...filters,page:1,contentType:e.target.value})}><option value="">全部类型</option><option>图文</option><option>视频</option><option>直播</option><option>其他</option></select></div>}
function MetricTable({data,page,setPage,onDetail,onEdit,onDelete}:{data:MetricList;page:number;setPage:(v:number)=>void;onDetail:(v:Metric)=>void;onEdit:(v:Metric)=>void;onDelete:(v:Metric)=>Promise<void>}){return <><TableContainer><table className="data-table metric-table"><thead><tr>{["日期","平台","账号","内容","曝光","播放","点赞","评论","收藏","分享","有效线索","试听","成交","成交金额","操作"].map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{data.items.map(m=><tr key={m.id}><td>{m.metric_date}</td><td>{m.platform}</td><td>{m.account_name}</td><td><button className="name-button" onClick={()=>onDetail(m)}>{m.content_title}</button></td><td>{number(m.exposure)}</td><td>{number(m.views)}</td><td>{number(m.likes)}</td><td>{number(m.comments)}</td><td>{number(m.favorites)}</td><td>{number(m.shares)}</td><td>{m.valid_leads}</td><td>{m.trial_bookings}</td><td>{m.deals}</td><td>{money(m.revenue)}</td><td><div className="row-actions"><button onClick={()=>onDetail(m)}>查看</button><button onClick={()=>onEdit(m)}>编辑</button><button className="danger-link" onClick={()=>void onDelete(m)}>删除</button></div></td></tr>)}</tbody></table></TableContainer><div className="pagination"><span>共 {data.total} 条</span><button className="button secondary" disabled={page<=1} onClick={()=>setPage(page-1)}>上一页</button><span>{page} / {Math.max(data.total_pages,1)}</span><button className="button secondary" disabled={page>=data.total_pages} onClick={()=>setPage(page+1)}>下一页</button></div></>}
