"use client";
import { FormEvent, useState } from "react";
import type { Account } from "@/features/accounts/types";
import type { MetricWrite } from "./types";

const numeric: [keyof MetricWrite, string][] = [["exposure","曝光"],["views","播放"],["likes","点赞"],["comments","评论"],["favorites","收藏"],["shares","分享"],["private_messages","私信"],["new_leads","新增线索"],["valid_leads","有效线索"],["high_intent_leads","高意向"],["trial_bookings","试听"],["deals","成交"]];
export function MetricFormDialog({initial, accounts, busy, error, onClose, onSubmit}:{initial:MetricWrite;accounts:Account[];busy:boolean;error:string|null;onClose:()=>void;onSubmit:(v:MetricWrite)=>Promise<void>}) {
  const [form,setForm]=useState(initial); const [validation,setValidation]=useState<string|null>(null);
  const set=(key:keyof MetricWrite,value:string|number|null)=>setForm(v=>({...v,[key]:value}));
  async function submit(e:FormEvent){e.preventDefault();if(!form.account_id||!form.metric_date||!form.content_title.trim()){setValidation("日期、账号和内容标题不能为空");return}if(numeric.some(([key])=>Number(form[key])<0)||Number(form.revenue)<0){setValidation("数值和成交金额不能为负数");return}setValidation(null);await onSubmit(form)}
  return <div className="dialog-backdrop"><section className="dialog metric-dialog" role="dialog" aria-modal="true" aria-labelledby="metric-form-title"><div className="dialog-header"><h2 id="metric-form-title">{initial.content_title?"编辑运营数据":"新增运营数据"}</h2><button className="icon-button" onClick={onClose} aria-label="关闭">×</button></div><form onSubmit={submit}><div className="form-grid"><label>日期<span>*</span><input type="date" value={form.metric_date} onChange={e=>set("metric_date",e.target.value)}/></label><label>账号<span>*</span><select value={form.account_id} onChange={e=>set("account_id",e.target.value)}><option value="">请选择账号</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.account_name}（{a.platform}）</option>)}</select></label><label className="full-field">内容标题<span>*</span><input value={form.content_title} onChange={e=>set("content_title",e.target.value)}/></label><label>内容类型<select value={form.content_type??""} onChange={e=>set("content_type",e.target.value||null)}><option>图文</option><option>视频</option><option>直播</option><option>其他</option></select></label><label>内容链接<input type="url" value={form.content_url??""} onChange={e=>set("content_url",e.target.value||null)}/></label>{numeric.map(([key,label])=><label key={key}>{label}<input type="number" min="0" value={String(form[key])} onChange={e=>set(key,Number(e.target.value))}/></label>)}<label>成交金额<input type="number" min="0" step="0.01" value={form.revenue} onChange={e=>set("revenue",e.target.value)}/></label><label className="full-field">备注<textarea rows={3} value={form.notes??""} onChange={e=>set("notes",e.target.value||null)}/></label></div>{validation||error?<p className="form-error" role="alert">{validation??error}</p>:null}<div className="dialog-actions"><button className="button secondary" type="button" onClick={onClose}>取消</button><button className="button primary" disabled={busy}>{busy?"保存中…":"保存"}</button></div></form></section></div>;
}
