"use client";
import { useCallback, useEffect, useState } from "react";
import { ErrorState } from "@/components/ui/error-state";
import { LoadingState } from "@/components/ui/loading-state";
import { PageHeader } from "@/components/ui/page-header";
import { TableContainer } from "@/components/ui/table-container";
import { createKeyword, deleteKeyword, exportKeywords, keywordStats, listKeywords, updateKeyword } from "./api";
import { KeywordFormDialog } from "./keyword-form-dialog";
import { KeywordImportDialog } from "./keyword-import-dialog";
import { emptyKeyword, type Keyword, type KeywordFilters, type KeywordList, type KeywordStats, type KeywordWrite } from "./types";
const initial:KeywordFilters={page:1,pageSize:20,platform:"",source:"",city:"",schoolStage:"",grade:"",subject:"",searchIntent:"",commercialIntent:"",contentStatus:"",status:"",search:""};
const filterOptions={platform:["小红书","抖音","视频号","百度","企微","其他","不限平台"],source:["人工录入","搜索联想","平台搜索","竞品账号","评论区","销售反馈","用户咨询","历史内容","Excel导入"],schoolStage:["小学","初中","高中"],commercialIntent:["低","中","高"],contentStatus:["未使用","已进入选题","已发布","已复盘"],status:["启用","停用","待审核"]};
export function KeywordsPage(){const[filters,setFilters]=useState(initial),[search,setSearch]=useState(""),[data,setData]=useState<KeywordList|null>(null),[stats,setStats]=useState<KeywordStats|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[form,setForm]=useState<Keyword|"create"|null>(null),[importOpen,setImportOpen]=useState(false),[saving,setSaving]=useState(false),[formError,setFormError]=useState<string|null>(null);const load=useCallback(async()=>{setLoading(true);setError(null);try{const[list,summary]=await Promise.all([listKeywords(filters),keywordStats(filters)]);setData(list);setStats(summary)}catch(e){setError(e instanceof Error?e.message:"关键词加载失败")}finally{setLoading(false)}},[filters]);useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);async function save(value:KeywordWrite){setSaving(true);setFormError(null);try{if(form==="create")await createKeyword(value);else if(form)await updateKeyword(form.id,value);setForm(null);await load()}catch(e){setFormError(e instanceof Error?e.message:"保存失败")}finally{setSaving(false)}}async function remove(item:Keyword){if(!window.confirm(`确认删除“${item.keyword}”吗？`))return;try{await deleteKeyword(item.id);await load()}catch(e){setError(e instanceof Error?e.message:"删除失败")}}async function download(){try{const blob=await exportKeywords(filters),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="关键词库.csv";a.click();URL.revokeObjectURL(url)}catch(e){setError(e instanceof Error?e.message:"导出失败")}}const cards:[string,keyof KeywordStats][]=[["关键词总数","total"],["高商业意图","high_commercial_intent"],["未使用关键词","unused"],["已进入选题","in_topics"],["平台数量","platform_count"],["学科数量","subject_count"]];return <><PageHeader title="关键词库" description="沉淀教培用户搜索需求与内容机会的关键词资产。" actions={<><button className="button secondary" onClick={()=>setImportOpen(true)}>导入</button><button className="button secondary" onClick={()=>void download()}>导出 CSV</button><button className="button primary" onClick={()=>setForm("create")}>新增关键词</button></>}/><div className="metric-grid">{cards.map(([label,key])=><div className="metric-card" key={key}><span>{label}</span><strong>{stats?.[key]??"—"}</strong></div>)}</div><section className="account-list-card"><Filters filters={filters} search={search} setSearch={setSearch} setFilters={setFilters}/>{loading?<LoadingState label="正在加载关键词"/>:error?<ErrorState message={error}/>:data?.items.length?<KeywordTable data={data} page={filters.page} onPage={page=>setFilters({...filters,page})} onEdit={setForm} onDelete={remove}/>:<div className="account-empty"><strong>暂无关键词</strong><p>可手动新增，或使用标准 CSV/XLSX 模板导入。</p></div>}</section>{form?<KeywordFormDialog initial={form==="create"?emptyKeyword:form} busy={saving} error={formError} onClose={()=>setForm(null)} onSubmit={save}/>:null}{importOpen?<KeywordImportDialog onClose={()=>setImportOpen(false)} onDone={load}/>:null}</>}
function Filters({filters,search,setSearch,setFilters}:{filters:KeywordFilters;search:string;setSearch:(v:string)=>void;setFilters:(v:KeywordFilters)=>void}){const select=(label:string,key:keyof KeywordFilters,values:string[])=><select aria-label={label} value={filters[key]} onChange={e=>setFilters({...filters,page:1,[key]:e.target.value})}><option value="">全部{label.replace("筛选","")}</option>{values.map(v=><option key={v}>{v}</option>)}</select>;return <div className="filter-bar keyword-filters"><form onSubmit={e=>{e.preventDefault();setFilters({...filters,page:1,search:search.trim()})}}><input aria-label="搜索关键词" placeholder="搜索关键词、痛点或备注" value={search} onChange={e=>setSearch(e.target.value)}/><button className="button secondary">搜索</button></form>{select("平台筛选","platform",filterOptions.platform)}{select("来源筛选","source",filterOptions.source)}<input aria-label="城市筛选" placeholder="城市" value={filters.city} onChange={e=>setFilters({...filters,page:1,city:e.target.value})}/>{select("学段筛选","schoolStage",filterOptions.schoolStage)}<input aria-label="年级筛选" placeholder="年级" value={filters.grade} onChange={e=>setFilters({...filters,page:1,grade:e.target.value})}/><input aria-label="学科筛选" placeholder="学科" value={filters.subject} onChange={e=>setFilters({...filters,page:1,subject:e.target.value})}/><input aria-label="搜索意图筛选" placeholder="搜索意图" value={filters.searchIntent} onChange={e=>setFilters({...filters,page:1,searchIntent:e.target.value})}/>{select("商业意图筛选","commercialIntent",filterOptions.commercialIntent)}{select("内容状态筛选","contentStatus",filterOptions.contentStatus)}{select("状态筛选","status",filterOptions.status)}</div>}
function Badge({value}:{value:string|null}){return value?<span className="status-pill">{value}</span>:<span>—</span>};function KeywordTable({data,page,onPage,onEdit,onDelete}:{data:KeywordList;page:number;onPage:(v:number)=>void;onEdit:(v:Keyword)=>void;onDelete:(v:Keyword)=>Promise<void>}){return <><TableContainer><table className="data-table keyword-table"><thead><tr>{["关键词","平台","城市","学段","年级","学科","搜索意图","商业意图","内容状态","来源","更新时间","操作"].map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{data.items.map(item=><tr key={item.id}><td><button className="name-button" onClick={()=>onEdit(item)}>{item.keyword}</button></td><td><Badge value={item.platform}/></td><td>{item.city??"—"}</td><td>{item.school_stage??"—"}</td><td>{item.grade??"—"}</td><td><Badge value={item.subject}/></td><td>{item.search_intent??"—"}</td><td><Badge value={item.commercial_intent}/></td><td><Badge value={item.content_status}/></td><td>{item.source??"—"}</td><td>{new Date(item.updated_at).toLocaleDateString("zh-CN")}</td><td><div className="row-actions"><button onClick={()=>onEdit(item)}>查看/编辑</button><button className="danger-link" onClick={()=>void onDelete(item)}>删除</button></div></td></tr>)}</tbody></table></TableContainer><div className="pagination"><span>共 {data.total} 条</span><button className="button secondary" disabled={page<=1} onClick={()=>onPage(page-1)}>上一页</button><span>{page} / {Math.max(data.total_pages,1)}</span><button className="button secondary" disabled={page>=data.total_pages} onClick={()=>onPage(page+1)}>下一页</button></div></>}
