import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { KnowledgePage } from "./knowledge-page";
const api=vi.hoisted(()=>({get:vi.fn(),post:vi.fn(),put:vi.fn(),delete:vi.fn()}));
vi.mock("@/lib/api/client",()=>({apiClient:api}));
const item={id:"k1",title:"课程优势",category:"课程资料",content:"正文内容",summary:"摘要",priority:"高",status:"启用",tags:["数学","家长"],updated_at:"2026-08-14T00:00:00Z"};
describe("KnowledgePage",()=>{beforeEach(()=>{vi.clearAllMocks();api.get.mockImplementation((p:string)=>p.startsWith("/knowledge/categories")?Promise.resolve({items:["课程资料"]}):p.startsWith("/knowledge/tags")?Promise.resolve({items:["数学","家长"]}):p.startsWith("/knowledge/stats")?Promise.resolve({total:1,category_count:1,high_priority:1,recently_updated:1}):Promise.resolve({items:[item]}));api.post.mockResolvedValue(item);api.put.mockResolvedValue(item);api.delete.mockResolvedValue(undefined)});
it("loads, searches and filters knowledge",async()=>{render(<KnowledgePage/>);await screen.findByRole("button",{name:"课程优势"});fireEvent.change(screen.getByLabelText("搜索知识"),{target:{value:"课程"}});fireEvent.change(screen.getByLabelText("分类筛选"),{target:{value:"课程资料"}});fireEvent.change(screen.getByLabelText("标签筛选"),{target:{value:"数学"}});await waitFor(()=>expect(api.get).toHaveBeenCalledWith(expect.stringContaining("tag=%E6%95%B0%E5%AD%A6")))});
it("creates, edits and deletes knowledge",async()=>{vi.spyOn(window,"confirm").mockReturnValue(true);render(<KnowledgePage/>);await screen.findByRole("button",{name:"课程优势"});fireEvent.click(screen.getByRole("button",{name:"新增知识"}));fireEvent.change(screen.getByLabelText("标题 *"),{target:{value:"新知识"}});fireEvent.change(screen.getByLabelText("分类 *"),{target:{value:"课程资料"}});fireEvent.change(screen.getByLabelText("正文"),{target:{value:"新的正文"}});fireEvent.click(screen.getByRole("button",{name:"保存"}));await waitFor(()=>expect(api.post).toHaveBeenCalled());fireEvent.click(screen.getByRole("button",{name:"课程优势"}));fireEvent.click(screen.getByRole("button",{name:"保存"}));await waitFor(()=>expect(api.put).toHaveBeenCalledWith("/knowledge/k1",expect.any(Object)));fireEvent.click(screen.getByRole("button",{name:"删除"}));await waitFor(()=>expect(api.delete).toHaveBeenCalledWith("/knowledge/k1"))})});
