"use client";
import { FormEvent,useEffect,useState } from "react";
import { PageHeader } from "@/components/ui/page-header";
import { TableContainer } from "@/components/ui/table-container";
import { apiClient } from "@/lib/api/client";
type Item={id:string;title:string;category:string;content:string;summary?:string;source_type?:string;source_name?:string;priority:string;status:string;tags:string[];updated_at:string}; type Stats={total:number;category_count:number;high_priority:number;recently_updated:number};
type FormItem=Omit<Item,"id"|"updated_at">&{id?:string;tag_text?:string};
const empty=():Omit<Item,"id"|"updated_at">=>({title:"",category:"",content:"",priority:"中",status:"启用",tags:[]});
export function KnowledgePage(){const[items,setItems]=useState<Item[]>([]),[categories,setCategories]=useState<string[]>([]),[tags,setTags]=useState<string[]>([]),[stats,setStats]=useState<Stats|null>(null),[form,setForm]=useState<(Omit<Item,"id"|"updated_at">&{id?:string})|null>(null),[filters,setFilters]=useState({search:"",category:"",status:"",priority:"",tag:""}); const[error,setError]=useState("");
 async function load(){const p=new URLSearchParams({page:"1",page_size:"20"});Object.entries(filters).forEach(([k,v])=>v&&p.set(k,v));const[a,b,c,d]=await Promise.all([apiClient.get<{items:Item[]}>(`/knowledge?${p}`),apiClient.get<{items:string[]}>("/knowledge/categories"),apiClient.get<{items:string[]}>("/knowledge/tags"),apiClient.get<Stats>("/knowledge/stats")]);setItems(a.items);setCategories(b.items);setTags(c.items);setStats(d)}
 useEffect(()=>{const t=setTimeout(()=>void load().catch(()=>setError("知识库加载失败")),0);return()=>clearTimeout(t)},[filters]);
 async function save(v:FormItem){if(!v.title.trim()||!v.content.trim()||!v.category){setError("请填写标题、分类和正文。");return} if(v.id)await apiClient.put(`/knowledge/${v.id}`,v);else await apiClient.post("/knowledge",v);setForm(null);await load()}
 return <><PageHeader title="知识库" description="沉淀公司、课程、销售与运营知识资产。" actions={<button className="button primary" onClick={()=>setForm(empty())}>新增知识</button>}/>{error&&<p role="alert" className="error-message">{error}</p>}<section className="stat-grid">{[["知识总量",stats?.total],["分类数量",stats?.category_count],["高优先级",stats?.high_priority],["最近更新",stats?.recently_updated]].map(([a,b])=><div className="stat-card" key={String(a)}><span>{a}</span><strong>{b??"-"}</strong></div>)}</section><section className="account-list-card"><div className="filter-bar"><input aria-label="搜索知识" value={filters.search} placeholder="搜索标题、正文或摘要" onChange={e=>setFilters({...filters,search:e.target.value})}/><select aria-label="分类筛选" value={filters.category} onChange={e=>setFilters({...filters,category:e.target.value})}><option value="">全部分类</option>{categories.map(x=><option key={x}>{x}</option>)}</select><select aria-label="状态筛选" value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">全部状态</option>{["启用","停用","草稿"].map(x=><option key={x}>{x}</option>)}</select><select aria-label="优先级筛选" value={filters.priority} onChange={e=>setFilters({...filters,priority:e.target.value})}><option value="">全部优先级</option>{["高","中","低"].map(x=><option key={x}>{x}</option>)}</select><select aria-label="标签筛选" value={filters.tag} onChange={e=>setFilters({...filters,tag:e.target.value})}><option value="">全部标签</option>{tags.map(x=><option key={x}>{x}</option>)}</select></div><TableContainer><table className="data-table"><thead><tr>{["标题","分类","标签","优先级","状态","更新时间","操作"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{items.map(v=><tr key={v.id}><td><button className="name-button" onClick={()=>setForm(v)}>{v.title}</button></td><td>{v.category}</td><td>{v.tags.join("、")||"-"}</td><td>{v.priority}</td><td>{v.status}</td><td>{new Date(v.updated_at).toLocaleDateString("zh-CN")}</td><td className="row-actions"><button onClick={()=>setForm(v)}>编辑</button><button className="danger-link" onClick={async()=>{if(confirm("确认删除该知识？")){await apiClient.delete(`/knowledge/${v.id}`);await load()}}}>删除</button></td></tr>)}</tbody></table></TableContainer></section>{form&&<Form value={form} categories={categories} onClose={()=>setForm(null)} onSave={save}/>}</>}
function Form({value,categories,onClose,onSave}:{value:FormItem;categories:string[];onClose:()=>void;onSave:(v:FormItem)=>Promise<void>}){const[v,setV]=useState(value);const submit=(e:FormEvent)=>{e.preventDefault();void onSave({...v,tags:(v.tag_text||"").split(",").map((x:string)=>x.trim()).filter(Boolean)})};return <div className="dialog-backdrop"><section className="dialog"><div className="dialog-header"><h2>{v.id?"编辑知识":"新增知识"}</h2><button onClick={onClose} aria-label="关闭">×</button></div><form className="form-grid" onSubmit={submit}><label className="full-field">标题 *<input required value={v.title} onChange={e=>setV({...v,title:e.target.value})}/></label><label>分类 *<select required value={v.category} onChange={e=>setV({...v,category:e.target.value})}><option value="">请选择</option>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label>优先级<select value={v.priority} onChange={e=>setV({...v,priority:e.target.value})}>{["高","中","低"].map(x=><option key={x}>{x}</option>)}</select></label><label>状态<select value={v.status} onChange={e=>setV({...v,status:e.target.value})}>{["启用","停用","草稿"].map(x=><option key={x}>{x}</option>)}</select></label><label>来源<input value={v.source_type||""} onChange={e=>setV({...v,source_type:e.target.value})}/></label><label className="full-field">标签（逗号分隔）<input aria-label="标签" defaultValue={(v.tags||[]).join(",")} onChange={e=>setV({...v,tag_text:e.target.value})}/></label><label className="full-field">摘要<textarea value={v.summary||""} onChange={e=>setV({...v,summary:e.target.value})}/></label><label className="full-field">正文 *<textarea required aria-label="正文" value={v.content} onChange={e=>setV({...v,content:e.target.value})}/></label><div className="dialog-actions full-field"><button type="button" className="button secondary" onClick={onClose}>取消</button><button className="button primary">保存</button></div></form></section></div>}
